apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: kaniko-build-and-push-run
spec:
  taskRef:
    name: kaniko-build-and-push
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: my-source
    - name: dockerconfig
      secret:
        secretName: my-secret
